"""initial

Revision ID: 2cf6f83894e0
Revises: 
Create Date: 2026-07-02 15:54:00.749374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision = '2cf6f83894e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=500), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('vps_servers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('user', sa.String(length=100), nullable=False),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('log_path', sa.String(length=500), nullable=True),
    sa.Column('password', sa.String(length=500), nullable=True),
    sa.Column('ssh_key', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_vps_servers_id'), 'vps_servers', ['id'], unique=False)
    op.create_table('log_collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vps_id', sa.Integer(), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('source_file', sa.String(length=500), nullable=True),
    sa.Column('total_lines', sa.Integer(), nullable=True),
    sa.Column('mode', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['vps_id'], ['vps_servers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_collections_id'), 'log_collections', ['id'], unique=False)
    op.create_table('endpoint_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('nb_requetes', sa.Integer(), nullable=True),
    sa.Column('latence_min_ms', sa.Float(), nullable=True),
    sa.Column('latence_p50_ms', sa.Float(), nullable=True),
    sa.Column('latence_moy_ms', sa.Float(), nullable=True),
    sa.Column('latence_p75_ms', sa.Float(), nullable=True),
    sa.Column('latence_p95_ms', sa.Float(), nullable=True),
    sa.Column('latence_p99_ms', sa.Float(), nullable=True),
    sa.Column('latence_max_ms', sa.Float(), nullable=True),
    sa.Column('latence_sum_ms', sa.Float(), nullable=True),
    sa.Column('upstream_moy_ms', sa.Float(), nullable=True),
    sa.Column('overhead_moy_ms', sa.Float(), nullable=True),
    sa.Column('body_min_mo', sa.Float(), nullable=True),
    sa.Column('body_p50_mo', sa.Float(), nullable=True),
    sa.Column('body_moy_mo', sa.Float(), nullable=True),
    sa.Column('body_p75_mo', sa.Float(), nullable=True),
    sa.Column('body_p95_mo', sa.Float(), nullable=True),
    sa.Column('body_p99_mo', sa.Float(), nullable=True),
    sa.Column('body_max_mo', sa.Float(), nullable=True),
    sa.Column('body_sum_mo', sa.Float(), nullable=True),
    sa.Column('taux_erreur_5xx', sa.Float(), nullable=True),
    sa.Column('taux_erreur_4xx', sa.Float(), nullable=True),
    sa.Column('premiere_occurrence_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('derniere_occurrence_utc', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['log_collections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_endpoint_stats_id'), 'endpoint_stats', ['id'], unique=False)
    op.create_table('log_entries',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('size', sa.BigInteger(), nullable=True),
    sa.Column('referrer', sa.Text(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('response_time', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['log_collections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_entries_id'), 'log_entries', ['id'], unique=False)
    op.create_table('log_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.Column('total_requests', sa.Integer(), nullable=True),
    sa.Column('unique_ips', sa.Integer(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=True),
    sa.Column('success_count', sa.Integer(), nullable=True),
    sa.Column('avg_size', sa.Float(), nullable=True),
    sa.Column('avg_resp_time', sa.Float(), nullable=True),
    sa.Column('top_paths', sa.Text(), nullable=True),
    sa.Column('top_ips', sa.Text(), nullable=True),
    sa.Column('status_dist', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['log_collections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_id')
    )
    op.create_index(op.f('ix_log_summaries_id'), 'log_summaries', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_log_summaries_id'), table_name='log_summaries')
    op.drop_table('log_summaries')
    op.drop_index(op.f('ix_log_entries_id'), table_name='log_entries')
    op.drop_table('log_entries')
    op.drop_index(op.f('ix_endpoint_stats_id'), table_name='endpoint_stats')
    op.drop_table('endpoint_stats')
    op.drop_index(op.f('ix_log_collections_id'), table_name='log_collections')
    op.drop_table('log_collections')
    op.drop_index(op.f('ix_vps_servers_id'), table_name='vps_servers')
    op.drop_table('vps_servers')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
